name: BlackduckSCA
on:
  push:
    branches: [ "main" ]
permissions:
  contents: read
  security-events: write
  issues: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        ACTIONS_STEP_DEBUG: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Black Duck SCA Scan
        id: black-duck-security-scan
        uses: blackduck-inc/black-duck-security-scan@v2.1.1
        env:
            DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
            ACTIONS_RUNNER_DEBUG: true
            ACTIONS_STEP_DEBUG: true
        with:
            github_token: ${{ secrets.GIT_PAT_TOKEN }}
            blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }}
            blackducksca_url: ${{ secrets.BLACKDUCK_URL }}
            blackducksca_reports_sarif_create: true
            include_diagnostics: true
