name: CI-BlackDuck-SCA
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        
      - name: Black Duck Scan
        id: blackduck_scan
        uses: bd-SrinathAkkem/black-duck-security-scan@SIGINT-2798
        continue-on-error: true
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          
        with:
          blackducksca_url: ${{ vars.BLACKDUCK_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }}
          # mark_build_status: UNSTABLE # SUCCESS, FAILURE (!= 0 OR 8), UNSTABLE & 8
          # return_status: true # Optional - Flag to return the exit code as an output (true/false)
          
          ### SCANNING: Optional fields
          # blackducksca_scan_failure_severities: 'BLOCKER,CRITICAL'
          
          ### FIX PULL REQUEST CREATION: Uncomment below to enable
          # blackducksca_fixpr_enabled: true
          # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when Fix PRs is enabled
          
          ### PULL REQUEST COMMENTS: Uncomment below to enable
          # blackducksca_prcomment_enabled: true 
          # github_token: ${{ secrets.GH_PAT_TOKEN }} # Required when PR comments is enabled

          ### SARIF report generation and upload to GitHub Adavanced Security: Uncomment below to enable
          # blackducksca_reports_sarif_create: true # Create Black Duck SARIF report and upload it as artifact
          # blackducksca_upload_sarif_report: true  # Upload Black Duck SARIF report in GitHub Advanced Security tab
        
      - name: Decide Pipeline
        run: |
          EXIT_CODE=${{ steps.blackduck_scan.outputs.status }}
          case $EXIT_CODE in
            0) echo "Black Duck Security Action workflow execution completed." ;;
            8) echo "Exit Code: 8 Policy violations detected treated as unstable proceeding with successful build." ;;
            *) echo "Failure (exit code $EXIT_CODE)"; exit 1 ;;
          esac
