name: PR Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run PR Review Bot
        uses: bd-SrinathAkkem/bd-ai-pr-review@macOS
        with:
          github_token: ${{ secrets.PR_REVIEW_TOKEN }}
          model: "codellama"
          mode: monitor

      - name: Check Complete
        run: |
          echo "PR Review Completed."
