name: CI-BlackDuck-SCA
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
 
      - name: Black Duck SCA PR Scan
        id: blackduck_scan
        uses: bd-SrinathAkkem/black-duck-security-scan@SIGINT-2798
        with:
          blackducksca_url: ${{ vars.BLACKDUCK_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }}
          blackducksca_scan_full: false
          blackducksca_prComment_enabled: true
          github_token: ${{ secrets.GD_TOKEN }}
          
      - name: Decide Pipeline
        run: |
          EXIT_CODE=${{ steps.blackduck_scan.outputs.exit_code }}
          case $EXIT_CODE in
            0) echo "Success" ;;
            8) echo "Policy violation, continuing" ;;
            *) echo "Failure (exit code $EXIT_CODE)"; exit 1 ;;
          esac
