name: CI-BlackDuck-SCA
on:
  pull_request:
    branches: [ main, master, develop, stage, release ]
 
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
 
      - name: Black Duck SCA PR Scan
        id: blackduck_scan
        continue-on-error: true  # Ignore failure and proceed
        uses: blackduck-inc/black-duck-security-scan@v2.0.0
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
        with:
          blackducksca_url: ${{ vars.BLACKDUCK_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }}
          blackducksca_scan_full: false
          blackducksca_prComment_enabled: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
 
      - name: Check Black Duck Exit Code
        run: |
          echo "Black Duck exit code: $BLACKDUCK_EXIT_CODE"
          if [ "$BLACKDUCK_EXIT_CODE" -eq 8 ]; then
            echo "Policy violation detected, but continuing due to testing phase."
          elif [ "$BLACKDUCK_EXIT_CODE" -ne 0 ]; then
            echo "Unexpected failure (exit code $BLACKDUCK_EXIT_CODE). Failing workflow."
            exit $BLACKDUCK_EXIT_CODE
          fi
        env:
          BLACKDUCK_EXIT_CODE: ${{ steps.blackduck_scan.outputs.exit_code || job.status == 'failure' && 8 || 0 }}
 
      - name: Next Step
        run: echo "Workflow continues regardless of Black Duck exit code 8."
 
