name: CI-BlackDuck-SCA
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Run Black Duck Scan
        id: blackduck_scan
        continue-on-error: true
        with:
          blackducksca_url: ${{ vars.BLACKDUCK_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }}
        run: |
          blackduck-inc/black-duck-security-scan@v2.0.0
          exitcode="$?"
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          exit "$exitcode"

      - name: Evaluate Scan Exit Code
        run: |
          echo "EXIT_CODE=${{ steps.blackduck_scan.outputs.exitcode }}" >> $GITHUB_ENV
          if [ "${{ steps.blackduck_scan.outputs.exitcode }}" -eq 8 ]; then
            echo "BLACKDUCK_STATUS=success" >> $GITHUB_ENV
          elif [ "${{ steps.blackduck_scan.outputs.exitcode }}" -ne 0 ]; then
            echo "BLACKDUCK_STATUS=failure" >> $GITHUB_ENV
            exit 1
          else
            echo "BLACKDUCK_STATUS=success" >> $GITHUB_ENV
          fi

      - name: Upload Black Duck Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: blackduck-report
          path: scan_output.log

      - name: Final Pipeline Status
        if: env.BLACKDUCK_STATUS == 'failure'
        run: exit 1