name: CI-BlackDuck-SCA-Basic
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Black Duck Scan
        uses: blackduck-inc/black-duck-security-scan@v2.0.0

        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}

        with:
          blackducksca_url: ${{ vars.BLACKDUCKSCA_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCKSCA_TOKEN }}
        id: blackduck_scan
        continue-on-error: true

      - name: Capture Black Duck Scan Exit Code
        run: |
            EXIT_CODE=$?
            echo "Exit Code from Black Duck Scan: $EXIT_CODE"
            echo "BLACKDUCK_EXIT_CODE=$EXIT_CODE" >> $GITHUB_ENV
            if [[ $EXIT_CODE -ne 0 ]]; then
              echo "Scan failed with exit code $EXIT_CODE"
              exit $EXIT_CODE
            fi

      - name: Evaluate Scan Exit Code
        run: |
          echo "EXIT_CODE=${{ steps.blackduck_scan.outputs.exitcode }}" >> $GITHUB_ENV
          if [ "${{ steps.blackduck_scan.outputs.exitcode }}" -eq 8 ]; then
            echo "BLACKDUCK_STATUS=success" >> $GITHUB_ENV
          elif [ "${{ steps.blackduck_scan.outputs.exitcode }}" -ne 0 ]; then
            echo "BLACKDUCK_STATUS=failure" >> $GITHUB_ENV
            exit 1
          else
            echo "BLACKDUCK_STATUS=success" >> $GITHUB_ENV
          fi

      - name: Upload Black Duck Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: blackduck-report
          path: scan_output.log

      - name: Final Pipeline Status
        if: env.BLACKDUCK_STATUS == 'failure'
        run: exit 1