name: CI-BlackDuck-SCA-Basic
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:

jobs:
  blackduck_scan:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Black Duck Security Scan and Capture Logs
        id: blackduck_scan
        run: |
          mkdir -p logs
          blackduck-inc/black-duck-security-scan@v2.0.0 \
            --blackducksca.url="${{ secrets.BLACKDUCK_URL }}" \
            --blackducksca.token="${{ secrets.BLACKDUCK_TOKEN }}" \
            2>&1 | tee logs/blackduck_scan.log || echo "EXIT_CODE=$?" >> logs/blackduck_exit_code.log

      - name: Extract Exit Code from Logs
        run: |
          EXIT_CODE=$(grep -o 'EXIT_CODE=[0-9]*' logs/blackduck_exit_code.log | awk -F= '{print $2}')
          echo "Detected Exit Code: $EXIT_CODE"
          if [[ -z "$EXIT_CODE" ]]; then
            echo "No exit code found in logs. Exiting with code 1."
            exit 1
          else
            exit $EXIT_CODE
          fi
