name: CI-BlackDuck-SCA-Basic
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Run linting and custom checks
        uses: actions/setup-node@v3
        run: |
          npm install
          npm run lint
          echo "Running additional custom checks..." 
