name: Major-Version-Upgrade
 
on:
  push:
    tags:
      - 'v*.*.*'
 
jobs:
  sync-version-tags:
    name: Version Upgrade
    runs-on: ubuntu-latest
 
    env:
      ENABLE_MAJOR_TAG: true
      ENABLE_LATEST_TAG: true
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Configure Git
        run: |
          git config user.name "Actions"
          git config user.email "actions@github.com"
 
      - name: Extract and validate version info
        id: version
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          echo "[INFO] Processing pushed tag: $TAG"
 
          if [[ "$TAG" =~ ^v([0-9]+)\.[0-9]+\.[0-9]+$ ]]; then
            MAJOR_TAG="v${BASH_REMATCH[1]}"
            echo "tag=$TAG" >> $GITHUB_OUTPUT
            echo "major=$MAJOR_TAG" >> $GITHUB_OUTPUT
            echo "[INFO] Valid semantic version detected: $TAG"
          else
            echo "[ERROR] Invalid tag format '$TAG'. Expected 'vX.Y.Z'"
            exit 1
          fi
 
      - name: Sync version
        run: |
          git fetch --tags
 
          TAG="${{ steps.version.outputs.tag }}"
          MAJOR="${{ steps.version.outputs.major }}"
 
          if [[ "${ENABLE_MAJOR_TAG}" == "true" ]]; then
            echo "[ACTION] Updating tag '$MAJOR' to point to '$TAG'"
            git tag -f "$MAJOR" "$TAG"
            git push origin "$MAJOR" --force
            echo "[SUCCESS] Tag '$MAJOR' now updated"
          else
            echo "[SKIP] Skipping major tag update (disabled)"
          fi
 
          if [[ "${ENABLE_LATEST_TAG}" == "true" ]]; then
            echo "[ACTION] Updating 'latest' tag to point to '$TAG'"
            git tag -f latest "$TAG"
            git push origin latest --force
            echo "[SUCCESS] Tag 'latest' now updated"
          else
            echo "[SKIP] Skipping 'latest' tag update (disabled)"
          fi
